name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | wc -l
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | head -1
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tail -1